---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    session: safety-critical
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      session: safety-critical
  template:
    metadata:
      labels:
        app: nginx
        session: safety-critical
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: session
                operator: In
                values:
                - safety-critical
              - key: safety
                operator: In
                values:
                - SWAL3
             
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: session 
                operator: In 
                values:
                - safety-critical
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80